[USH-873] Changed Text From Delete 1 posts to Delete 1 Post.
ushahidi/platform-client-mzima pull request #1001
Opened 2024-04-04 13:13 UTC by MugoBrian

This PR fixes this two issues since they are related and affected the same area:
1. [Say "....deleted 1 post..." instead of "...deleted 1 posts..." after deleting 1 post](https://linear.app/ushahidi/issue/USH-873/say-deleted-1-post-instead-of-deleted-1-posts-after-deleting-1-post).
2. ["OK, Sounds good" text.](https://linear.app/ushahidi/issue/USH-890/ok-sounds-good-text)

Changes made:
1. Changed the grammar in the deleted 1 posts confirm modal description affected in the `feed.component.ts` and `post-head.component.ts`.
2. Edited the `en.json` accordingly.
3. Centralized "Success" text alignment.

2024-04-04 13:14 UTC, MugoBrian commented
Hello @AmTryingMyBest and @tuxpiper, this PR is ready for review.

2024-04-09 16:32 UTC, tuxpiper commented
Hi @MugoBrian . Sorry, I'm not sure I can review this one properly. @Ifycode could you please take a look?

2024-04-15 13:53 UTC, ushahidlee commented on apps/web-mzima-client/src/app/feed/feed.component.ts
> +      const postWord = count === 1 ? `post` : `posts`;
Please change from backticks to quotes

2024-04-15 13:53 UTC, ushahidlee requested changes
Looks good.

2024-04-17 09:08 UTC, MugoBrian commented on apps/web-mzima-client/src/app/feed/feed.component.ts
> +      const postWord = count === 1 ? `post` : `posts`;
Ok. On it.

2024-04-17 09:20 UTC, MugoBrian commented
Hello @ushahidlee. I have made the necessary changes.

2024-04-24 18:26 UTC, ushahidlee approved these changes
Great, thanks @MugoBrian !

2024-04-25 04:22 UTC, merged