Provided a descriptive alt text for the company info image
ushahidi/platform-client-mzima pull request #1121
Opened 2024-06-20 07:24 UTC by kivuvarosekivuvan

## Engineer's Checklist
- This PR addresses the issue of the redundant alt text for the Company-info Image. The current alt text is the same as the text "Company's info" displayed next to it, which is unnecessary and repetitive for users of screen readers or when the image is unavailable.

### Changes Made
- The `[alt]` attribute of the `<img>` element has been changed from **`[alt]="title"`** to **`[alt]="'Company logo'"`**. This ensures that the alt text provides additional information about the image that is not already available in the "Company info" text next to the image, improving the accessibility of the content for users who are unable to see the image.

**Concern:**    @Ifycode and @Angamanga  A question on the change: Is it better to call it the deployment's logo or image. Which do you think is the best for this case?

### How to test the changes
- This change has been tested manually by launching the local host, navigating to the company info section, and observing the alt text used for the image. The updated alt text accurately describes the image as the "Company logo" and no longer repeats the title text. 

- It has also been tested using screen reader to read out the purpose of the image

![Screenshot from 2024-06-20 10-22-03](https://github.com/ushahidi/platform-client-mzima/assets/124133577/f766fcad-91c1-41ba-acb1-9387f62fbfba)

2024-06-20 07:27 UTC, kivuvarosekivuvan commented
@Ifycode and @Angamanga This PR is ready for review

2024-06-21 07:42 UTC, Ifycode approved these changes

2024-06-21 07:48 UTC, Ifycode requested changes

2024-06-21 07:48 UTC, Ifycode commented on apps/web-mzima-client/src/app/shared/components/company-info/company-info.component.html
> +        [alt]="'Logo for ' + title + ' deployment'"
Logo is fine for now I believe. Although it probably may not be their logo, may even be just a random image... But it's representing the deployment logo.

For consistency, maybe use this instead:
````
[alt]="title + ' deployment Logo'"
````

2024-06-21 07:48 UTC, kivuvarosekivuvan commented
@Ifycode and @Angamanga A question on the change: Is it better to call it the deployment's logo or image. Which do you think is the best for this case?

2024-06-21 07:50 UTC, Ifycode commented
See comment here: https://github.com/ushahidi/platform-client-mzima/pull/1121#discussion_r1648557675
@kivuvarosekivuvan

2024-06-24 04:39 UTC, kivuvarosekivuvan commented
@Ifycode Changes upto date. Ready for another review💯

2024-06-24 05:30 UTC, Ifycode approved these changes

2024-06-24 05:31 UTC, merged