[USH-1510] Use only parameters for posts in web client
ushahidi/platform-client-mzima pull request #1418
Opened 2024-11-04 10:35 UTC by Ifycode

2024-11-13 18:39 UTC, Angamanga requested changes
There is one silly side-effect on this change, when trying to publish a post from the post-list, the post_content isn't there so the code cannot properly check that all required tasks are completed. It is happening here:https://github.com/ushahidi/platform-client-mzima/blob/development/apps/web-mzima-client/src/app/post/post-head/post-head.component.ts#L86. I think that in the cases when a user is publishing from the feed-view, we would actually need to get the full post. Maybe you can add a check to see if the full post is there, and if not, get it and do the check? It only applies to when the user clicks on "Publish" in the feed-view, not in detailed view.

2024-11-13 18:39 UTC, Angamanga commented on apps/web-mzima-client/src/app/post/post-preview/post-preview.component.ts
> -      if (this.post.post_content) {
Hehe, finally we got rid of "TODO: Optimise" 🤗

2024-11-14 11:08 UTC, Ifycode commented
I've added the change, do this work? @Angamanga

2024-11-15 14:41 UTC, Ifycode commented
This is ready for review too @Angamanga

2024-11-18 10:16 UTC, Angamanga requested changes
Just a tiny change, see my comment in the code 🙌

2024-11-18 10:16 UTC, Angamanga commented on apps/web-mzima-client/src/app/feed/feed.component.ts
> +        }
Just a tiny thing, you need to return the result of the isAllRequiredCompleted to be ably to save it in the uncompletedPosts array 👍 If you do that, it works fine!

2024-11-19 14:11 UTC, Ifycode commented
Ready @Angamanga

2024-11-20 08:30 UTC, Angamanga approved these changes
Approved 🙌

2024-11-21 10:07 UTC, merged