Allow user to delete their own contact
ushahidi/platform-client-mzima pull request #769
Opened 2024-02-12 15:54 UTC by ushahidlee

Change the visibility of the delete button, to allow a user to delete their own contact.

2024-02-13 10:06 UTC, Ifycode requested changes

2024-02-13 10:06 UTC, Ifycode commented on apps/web-mzima-client/src/app/shared/components/account-settings-modal/account-settings-modal.component.ts
> -
The remove button & modal shows up for non-admin user @ushahidlee 👍🏼
But the response from the contacts API endpoint is a 403-forbidden for such user - images below.

Question: Is there a separate fix for this already on the backend that gives such users access and that one can test with yet?

#

<img width="1641" alt="Screenshot 2024-02-13 at 10 51 55" src="https://github.com/ushahidi/platform-client-mzima/assets/45185388/f8ff7239-2e63-4983-b1b4-cbbbb28f3b88">

#

<img width="1641" alt="Screenshot 2024-02-13 at 10 53 03" src="https://github.com/ushahidi/platform-client-mzima/assets/45185388/152d9730-2e39-4c8e-9f37-b8a9f54acfb4">

2024-02-13 10:10 UTC, ushahidlee commented on apps/web-mzima-client/src/app/shared/components/account-settings-modal/account-settings-modal.component.ts
> -
Yeah there is a separate PR for backend.

https://github.com/ushahidi/platform/pull/4716

2024-02-14 15:24 UTC, Ifycode approved these changes

2024-02-14 15:24 UTC, Ifycode commented on apps/web-mzima-client/src/app/shared/components/account-settings-modal/account-settings-modal.component.ts
> -
All right then

2024-02-15 07:47 UTC, Angamanga approved these changes
All good 🙌

2024-02-15 11:36 UTC, merged