Added a cancel button on the general page in settings which has a capability of clearing the form once it is clicked
ushahidi/platform-client-mzima pull request #813
Opened 2024-03-05 20:50 UTC by kivuvarosekivuvan

# Engineers Checklist

## What this PR does?
- Introduce a 'Cancel' button on the general settings page to allow users to discard changes without saving them.

## How can it be tested?
- Launch the local server
- Login/signup to have the settings feature
- Navigate to the general page in settings
- Scroll to the bottom,click on the 'cancel' button

# Where is it documented?
- [https://github.com/orgs/ushahidi/projects/18/views/1?pane=issue&itemId=55115846](url)

## UI Update
![Screenshot from 2024-03-05 23-34-27](https://github.com/ushahidi/platform-client-mzima/assets/124133577/bf8e5952-e9ce-4f30-b07d-ad3734e149de)

2024-03-13 10:06 UTC, Angamanga commented
Thank you for your PR and the very detailed description of your work @kivuvarosekivuvan 🙏. @ushahidlee Could you please review?

2024-03-13 10:22 UTC, kivuvarosekivuvan commented
@Angamanga Thank you for the compliment. Awaiting for review from @ushahidlee

2024-03-18 11:18 UTC, Angamanga requested changes
Thank you for this PR @kivuvarosekivuvan, great work, this issue had many steps to work through. A few comments:
1. I noticed that if I don't make any changes, and press "Cancel", the original text is also wiped from the form. I think you could look at this row: https://github.com/ushahidi/platform-client-mzima/pull/813/files#diff-bcd3dc0cdd5e9cadc9d7cf27b546e46462ffd7d7c62a96f97935e1041c6e06a9L61. That is how the form is filled from the beginning.
2. Great work at creating the confirm-dialog. However, we already have a modal-service that you could use, take a look how it is used when cancelling editing a post here: https://github.com/ushahidi/platform-client-mzima/blob/development/apps/web-mzima-client/src/app/post/post-edit/post-edit.component.ts#L696-L701

Let me know if you have any questions and good work so far!

2024-03-18 11:31 UTC, kivuvarosekivuvan commented
@Angamanga Thank you so much for this review :pray: .However, I didn't fully grasp the meaning of the first comment. I would greatly appreciated if you could provide further clarification in order for me to comprehend it accurately and proceed with its execution.

 The second comment is clear, and I will start working on it right away.

2024-03-20 10:04 UTC, kivuvarosekivuvan commented
@Angamanga and @ushahidleeI have made the requested changes based on your suggestions. Could you please take a moment to review the updated version and provide me feedback 🙏?

2024-03-20 19:12 UTC, Angamanga commented
Hi @kivuvarosekivuvan! Did you figure out my first comment above? I meant that if I press cancel, I would assume the original, saved values should be visible in the form, it should not result in the form being empty 👍

2024-03-20 19:47 UTC, kivuvarosekivuvan commented
@Angamanga Thanks I get it now. Let me work on it right away

2024-03-25 20:49 UTC, Angamanga requested changes
@kivuvarosekivuvan Great work! Nearly there :) Just a few comments in the code.

2024-03-25 20:49 UTC, Angamanga commented on package-lock.json
Remove this file from the PR

2024-03-25 20:49 UTC, Angamanga commented on package.json
Could you revert back to the old versions here if they are not needed by this PR?

2024-03-25 20:53 UTC, kivuvarosekivuvan commented on package.json
Sure thing! I will do that @Angamanga

2024-03-25 20:54 UTC, kivuvarosekivuvan commented on package-lock.json
I will get rid of it here👌

2024-03-26 12:50 UTC, kivuvarosekivuvan commented on package-lock.json
@Angamanga Could you please confirm if I did it as expected :pray: , I have made changes.

2024-03-27 20:16 UTC, Angamanga approved these changes
It works now so approving! If you would like, try removing the package-lock entirely from the PR, not from the project itself, so it has the same state as the development-branch. But if its too tricky, I can sort it out before merging :)

2024-03-27 20:16 UTC, Angamanga commented
@Angamanga Remove package-lock before merging

2024-03-27 20:21 UTC, kivuvarosekivuvan commented
> It works now so approving! If you would like, try removing the package-lock entirely from the PR, not from the project itself, so it has the same state as the development-branch. But if its too tricky, I can sort it out before merging :) 

Hello @Angamanga, I tried to remove it but it was not working as I expected, I can try it again and let you know once I manage it

2024-06-25 04:38 UTC, Angamanga approved these changes

2024-06-26 06:25 UTC, Angamanga commented
Merged in this PR: https://github.com/ushahidi/platform-client-mzima/pull/1130

2024-06-26 06:25 UTC, closed without merging