fix "Filtering" onboarding modal is absent for Arabic translation #4738
ushahidi/platform-client-mzima pull request #821
Opened 2024-03-06 12:11 UTC by Felysilver

When a language is changed to Arabic which is a Right to left language (RTL), The heading of the onboarding modal for example "Filtering" and others, changes text direction. This makes the text run into the close-button as shown here

screanshort before

![filter-two](https://github.com/ushahidi/platform-client-mzima/assets/162261453/072bfef5-71e0-41b8-ad33-e6a94090a6e1)
![filter-4](https://github.com/ushahidi/platform-client-mzima/assets/162261453/4ed7f526-9c97-48bc-b55f-cef61431eda6)

 I have come up with the solutiion uniform to both RLT & LTR languages that fixes all modals.

screanshot after fix
![fixed-4](https://github.com/ushahidi/platform-client-mzima/assets/162261453/4f4e9514-198c-4b1b-a6ed-a84d4706aa7b)

2024-03-06 12:14 UTC, Felysilver commented
@Angamanga , @tuxpiper ask for a review of this PR. Does it fix the issue to your expectations? Thanks Plz!

2024-03-13 18:08 UTC, Angamanga commented
Thank you @Felysilver! @Ifycode Could you please review this?

2024-03-20 15:00 UTC, Ifycode requested changes

2024-03-20 15:00 UTC, Ifycode commented on apps/web-mzima-client/src/app/shared/components/onboarding/onboarding.component.scss
>      margin: 0 -4px 24px;
Hello @Felysilver 
This fix you sent is different from and does not address what you were asked to do in the issue. 

Steps to reproduce the issue you were asked to fix:
- Go to /map
- Change your language to arabic
- In your dev tool, click on "application" tab, go to "storage" and clear site data
- Reload the page (while still in language Arabic), you will see the onboarding modal popup
- Keep going to the next modal until you get to "sorting". The overlay is there but the modal is no longer there.

2024-03-20 15:22 UTC, Ifycode commented on apps/web-mzima-client/src/app/shared/components/onboarding/onboarding.component.scss
>      margin: 0 -4px 24px;
So here's what you can do @Felysilver 
1. You can create another github issue for this particular fix you are submitting in this PR, then link that new issue you created to this PR - I will then review it.
2. For my [comment above here](https://github.com/ushahidi/platform-client-mzima/pull/821#discussion_r1532243425), would you like to also fix this issue - now that I have shared how to reproduce it?

2024-03-20 16:45 UTC, Felysilver commented on apps/web-mzima-client/src/app/shared/components/onboarding/onboarding.component.scss
>      margin: 0 -4px 24px;
Thanks @Ifycode , actually this is the [PR-#857](https://github.com/ushahidi/platform-client-mzima/pull/857) I created for that, may look at it.

2024-06-27 04:34 UTC, closed without merging