Buttons Must have discernible text for screen readers
ushahidi/platform-client-mzima pull request #830
Opened 2024-03-07 09:53 UTC by MundiaNderi

## Description
The toggle button did not have inner text that was visible to screen readers.  I added the aria label because the  button does not have visible inner text.

## Fixes 
This PR fixes the issue: https://github.com/ushahidi/platform/issues/4761

2024-03-11 09:20 UTC, MundiaNderi commented
@Angamanga this PR is ready for review.

2024-03-13 18:52 UTC, Angamanga commented
Hi @MundiaNderi! Thank you for your PR! Usually, we aim to solve one issue per PR, it looks like this PR solves 3 issues? Could you try separating the things you have fixed into three separate PRs? OR, if they are very related, add a description to this PR describing all changes made as well as a checklist on how to test the changes? Thank you :)

2024-03-13 19:17 UTC, MundiaNderi commented
@Angamanga all the issues were related, in that the buttons and icons were not screen reader supported so I thought that having many PRs would be redundant, but going forward I'll keep it to one issue per PR. I have made the changes and I have added instructions on how to test the changes.

2024-03-15 14:23 UTC, Angamanga commented
Ok, thanks for the clarification @MundiaNderi 🙏

2024-03-18 15:02 UTC, Angamanga requested changes
What error do you get when trying to add the aria-label to the mzima-button? It is possible to add an aria-label, to the button, but the syntax may be a little bit different, look at how it is solved here: 
https://github.com/ushahidi/platform-client-mzima/blob/development/apps/web-mzima-client/src/app/shared/components/filter-control/filter-control.component.html#L147

2024-03-18 20:21 UTC, MundiaNderi commented
<img width="912" alt="Screenshot 2024-03-18 at 22 45 29" src="https://github.com/ushahidi/platform-client-mzima/assets/98798719/534f19c0-eda9-4fe5-87e7-1e51326a66d0">
 this is the error. I'll explore the posted solution and revert.

2024-03-20 07:37 UTC, MundiaNderi commented
@Angamanga I went through your proposed solution and even though it didn't work for me, I found the solution.
I found the button component which generically sets the aria-label dynamically based on the ariaLabel property and ended up using the ariaLabel property for the mzima button. [attr.aria-label]="ariaLabel" . I also deleted the css classes that I had used to set/hide span class.

This PR is now ready for review. 

<img width="858" alt="Screenshot 2024-03-20 at 09 30 53" src="https://github.com/ushahidi/platform-client-mzima/assets/98798719/ece834a3-3a1c-402c-80f0-c02e91562f63">

2024-03-27 19:24 UTC, Angamanga requested changes
Almost there, just remove the package-lock file from the PR 👍

2024-03-27 19:24 UTC, Angamanga commented on package-lock.json
Remove this file from the PR 👍

2024-03-28 20:41 UTC, MundiaNderi commented
@Angamanga happy to report that this is fixed.

2024-04-08 14:59 UTC, Angamanga approved these changes
Excellent! Approved :) 👍

2024-10-07 08:15 UTC, closed without merging