fix: disable viewing and updating collections without correct permissions
ushahidi/platform-client-mzima pull request #832
Opened 2024-03-07 12:17 UTC by mannyAndem

This pull request fixes issue [4739](https://github.com/orgs/ushahidi/projects/18/views/1?pane=issue&itemId=55115848) which focused on disabling access to view and modify collections without having the correct permissions.

2024-03-15 13:02 UTC, Angamanga commented
Thank you for your PR @mannyAndem  🙏. Could you please add a short description and a checklist for testing the fix as well and then we'll review it 👍

2024-03-17 06:23 UTC, mannyAndem commented
@Angamanga sorry for replying late, the internet downtime hit real bad. But I'll do this pronto :)

2024-03-17 11:36 UTC, mannyAndem commented
This pull request fixed the issue of allowing only users with the correct privileges to view and update collections. Only users with "read" permissions can view collections while only those with "update" permissions can add a post to a collection. Posts with visibility status of "everyone" will be seen regardless of the permission level of the current user (even if the user isn't logged in at all).

To test the fix:

- [ ] As a user with admin privileges, create a collection and set its visibility to any level except everyone.
- [ ] Log out.
- [ ] You shouldn't be able to view the newly created collection.
- [ ] Collection should be visible to everyone with read privilege.

Please let me know if there's anything that requires tweaking @Angamanga :)

2024-03-19 12:22 UTC, mannyAndem commented
I rewrote the permissions logic to be encapsulated in a ```checkReadPrivileges``` function which checks if user fulfils any of the conditions necessary to view a specific collection. @Angamanga :)

2024-03-21 13:39 UTC, Angamanga requested changes
Thank you for your contribution @mannyAndem! It seems like I still can add posts to collections when not having the correct priviliges, if I login as a "member", I can still add posts to collections, which I should not be able to. Could you please take a look?

2024-03-21 16:48 UTC, mannyAndem commented
Hmm, that's odd, I might have overlooked something. Will check right now!

2024-03-21 19:25 UTC, mannyAndem commented
@Angamanga, I think I've got it. Hid the add post to collection button when user does not have any of the "Manage Posts" or  "Manage Collections and Saved Searches" permissions as per the user documentation. Could you take a look now? :)

2024-03-25 20:54 UTC, Angamanga requested changes
Good job, just a tiny change to remove a forgotten console.log :)

2024-03-25 20:54 UTC, Angamanga commented on apps/web-mzima-client/src/app/shared/components/collections/collections.component.ts
>        },
Nearly there, just remove this console log :)

2024-03-25 21:01 UTC, mannyAndem commented
Done @Angamanga :)

2024-03-27 20:07 UTC, Angamanga approved these changes
Thank you! Approved!

2024-03-27 20:16 UTC, mannyAndem commented
Arigato @Angamanga :)

2024-04-03 12:31 UTC, merged