[Outreachy Task Submission] Resolved Map Page Button component accessibility issue
ushahidi/platform-client-mzima pull request #882
Opened 2024-03-14 03:19 UTC by crocmons

### PR Description:
This PR addresses the accessibility issue identified on the Map Page, where the `mzima-client-button` component lacked discernible text for screen readers on the "Create Post" and "Search Icon" buttons.

### Changes Made:
- Implemented dynamic generation of `aria-label` attributes based on the buttons' content.
- Ensured that buttons include visible text or descriptive labels.

### Testing:
- Verified the changes locally by navigating to the Map Page and using screen readers to interact with the buttons.
- Ran accessibility tests to ensure compliance with accessibility guidelines.
- Tested on various browsers and screen reader combinations to ensure compatibility.

- **Issue Number** : [#4825](https://github.com/ushahidi/platform/issues/4825)

![Screenshot (664)](https://github.com/ushahidi/platform-client-mzima/assets/106610322/000cf58a-2f72-4bb5-9d93-fbe0de0b57c8)

2024-03-24 12:09 UTC, Angamanga requested changes
Nice findings, see my comments in the code for a few changes. For the package-lock file, remove it from the PR, as well as the library in package.json, I think it might be a rest from some other testing in the client :)

2024-03-24 12:09 UTC, Angamanga commented on apps/web-mzima-client/src/app/shared/components/submit-post-button/submit-post-button.component.scss
> +}
Could you move this to the general styles-css instead? I think it would be useful in many places 👍

2024-03-24 12:09 UTC, Angamanga commented on libs/mzima-ui/src/lib/button/button.component.ts
> +  }
If the button actually contains text, could we use that here as well? Or is this only for buttons without text?

2024-03-24 12:09 UTC, Angamanga commented on package.json
>      "swiper": "^9.2.4",
This is not needed for this change, right? In that case, remove it from the PR

2024-03-24 13:17 UTC, crocmons commented on apps/web-mzima-client/src/app/shared/components/submit-post-button/submit-post-button.component.scss
> +}
noted, sure, I will do that

2024-03-24 20:45 UTC, crocmons commented
@Angamanga this pr is updated now..kindly review it.

2024-03-27 19:51 UTC, Angamanga approved these changes
Thank you for this! Approved!

2024-03-27 19:54 UTC, crocmons commented
> Thank you for this! Approved!

thank you so much @Angamanga

2024-10-07 08:15 UTC, closed without merging