add skip to main content link
ushahidi/platform-client-mzima pull request #936
Opened 2024-03-22 14:34 UTC by mannyAndem

This pr fixes issue [#4860](https://github.com/ushahidi/platform/issues/4860) which talked about users not being able to skip navigation panel. This fix adds a "Skip to main content" button that only becomes visible when tabbed into. Clicking it skips the navigation and search and gets to the main content of the page.

To test:

- Using the tab key, start navigating through the page.
- Just after the "Add new post" button and before the navigation, a "skip to main content" should appear.
- Activating it (by pressing space or enter key depending on browser settings) should skip to the main content of the page

2024-03-25 20:23 UTC, Angamanga requested changes
Very nice addition :) Just a small change-request, see my comment in the code!

2024-03-25 20:23 UTC, Angamanga commented on apps/web-mzima-client/src/app/shared/components/main/sidebar/sidebar.component.scss
> +  .visibly-hidden {
Could you move this to styles.scss instead? I think its useful in more places than just here :)

2024-03-25 21:05 UTC, mannyAndem commented
Done @Angamanga :)

2024-03-27 20:07 UTC, Angamanga approved these changes
Thank you! Approved!

2024-03-27 20:18 UTC, mannyAndem commented
Thank you!

2024-10-07 08:15 UTC, closed without merging