[Outreachy Task Submission]Phone Number and Email Validation Error Not Displayed in Notification Settings #4884
ushahidi/platform-client-mzima pull request #959
Opened 2024-03-26 19:46 UTC by Appleeyes

## Description

This pull request addresses the issue https://github.com/ushahidi/platform/issues/4884 where validation errors were not displayed correctly in the Notification Settings modal component. Previously, when users inputted an invalid email format or phone number format into the respective input fields, no validation error message was shown, leading to user confusion.

![accountPhone](https://github.com/ushahidi/platform-client-mzima/assets/86308689/40a8d20e-a599-4a2c-9ee0-ba102a136dac)

![accountEmail](https://github.com/ushahidi/platform-client-mzima/assets/86308689/528738b5-7dd9-4565-b632-38f204d1d307)

To address this issue, the validation logic for email and phone number inputs has been updated in the Notification Settings modal component. The email input field now correctly validates email formats using Angular's built-in Validators.email validator, while the phone number input field validates phone number formats using a custom regular expression pattern.

Additionally, the UI has been configured to display appropriate error messages next to the input fields. This enhancement improves the user experience by providing clear feedback to users about incorrect inputs, prompting them to correct the format accordingly.

![phoneError](https://github.com/ushahidi/platform-client-mzima/assets/86308689/d1d4e603-1819-48c2-8e81-5961f75d0394)

![emailError](https://github.com/ushahidi/platform-client-mzima/assets/86308689/2d4ef2c4-b899-4aaf-bc63-e164d10e9cbb)

## Changes Made

- Updated the validation logic for email and phone number inputs in the Notification Settings modal component.
- Utilized Angular's Validators.email validator for email validation.
- Implemented a custom regular expression pattern for phone number validation.
- Configured the UI to display error messages next to the input fields when validation fails.

## Testing

- Manually tested the Notification Settings modal component.
- Inputted various email and phone number formats, including valid and invalid ones.
- Verified that error messages are displayed correctly for invalid inputs.
- Ensured that error messages disappear when valid inputs are provided.
- Tested the functionality across different browsers and screen sizes to ensure consistency.

This pull request resolves the issue of validation errors not being displayed correctly in the Notification Settings, enhancing the user experience and preventing potential issues arising from incorrect inputs.

2024-03-29 07:02 UTC, tuxpiper requested changes
Very nice that you found the issue, documented it and solved it. 🙌 

Please take a look at my request for a small change. I think that's all it needs to be approved.

2024-03-29 07:02 UTC, tuxpiper commented on apps/web-mzima-client/src/env.json
This change is not useful to others. @Appleeyes could you please remove it from the PR?

2024-03-29 07:45 UTC, tuxpiper commented
@Angamanga this one is close to approval, just a tiny detail pending

2024-03-29 08:00 UTC, Appleeyes commented on apps/web-mzima-client/src/env.json
Thank you @tuxpiper I removed it.

2024-04-02 19:20 UTC, tuxpiper approved these changes
Approved :+1: Nice job, thank you!

2024-10-07 08:22 UTC, closed without merging