included an icon library in index.html to use the delete icon under s…
ushahidi/platform-client-mzima pull request #980
Opened 2024-03-28 23:05 UTC by Cecil-o

Included an icon library in index.html to use the delete icon under surveys component,
called the method and align the icon to the end in CSS. This solve the issue for when a user wants to carry out single action.

2024-04-02 19:47 UTC, tuxpiper requested changes
Thank you for the contribution!

Could you please add some more details to the issue that you created (ushahidi/platform#4894)? It's difficult to follow and make sure I understand what you are intending to fix here.

2024-04-02 19:47 UTC, tuxpiper commented on apps/web-mzima-client/src/env.json
Please remove this change, it's not useful to others

2024-04-02 19:47 UTC, tuxpiper commented
> Thank you for the contribution!
> 
> Could you please add some more details to the issue that you created ([ushahidi/platform#4894](https://github.com/ushahidi/platform/issues/4894))? It's difficult to follow and make sure I understand what you are intending to fix here.

A screenshot would be helpful

2024-04-11 05:22 UTC, Cecil-o commented
> Thank you for the contribution!
> 
> Could you please add some more details to the issue that you created ([ushahidi/platform#4894](https://github.com/ushahidi/platform/issues/4894))? It's difficult to follow and make sure I understand what you are intending to fix here.

Hello, my apology for the delay, had some technical issue. The changes made should be clear now. Thanks

2024-10-07 08:23 UTC, closed without merging